apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: szokeb-kafka
spec:
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: szoekebence/kafka-producer:0.0.1
          imagePullPolicy: Always
          env:
            - name: DELAY_MS
              value: "0"
            - name: BOOTSTRAP_SERVER
              value: "szokeb-kafka-kafka-bootstrap:9092"
            - name: LINGER_MS
              value: "50"
            - name: BATCH_SIZE_KB
              value: "256"
            - name: PRODUCING_TIME_MIN
              value: "10"
          resources:
            limits:
              memory: "1024Mi"
              cpu: "4000m"